version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: helpdesk-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: helpdesk_db
      POSTGRES_USER: helpdesk_user
      POSTGRES_PASSWORD: 29999login
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: